/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CozyClock {
    }
}
declare global {
    interface HTMLCozyClockElement extends Components.CozyClock, HTMLStencilElement {
    }
    var HTMLCozyClockElement: {
        prototype: HTMLCozyClockElement;
        new (): HTMLCozyClockElement;
    };
    interface HTMLElementTagNameMap {
        "cozy-clock": HTMLCozyClockElement;
    }
}
declare namespace LocalJSX {
    interface CozyClock {
    }
    interface IntrinsicElements {
        "cozy-clock": CozyClock;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cozy-clock": LocalJSX.CozyClock & JSXBase.HTMLAttributes<HTMLCozyClockElement>;
        }
    }
}
